### ISSUE TITLE
Query param key/values are separated by a - instead of =

### ISSUE THREAD

**Issue by mikejwhitehead** [faasflow/lib#2]
Usage of query parameters causes a bad request sent to the function, like in this example response

`/?name-server01.example.com - 400 Bad Request - ContentLength: 24`

https://github.com/faasflow/lib/blob/13757550c22ae68743444cf351f299d88497bd9c/openfaas/faas_operation.go#L135

This should be `fmt.Sprintf("%s=%s", key, value)`

Happy to submit a PR

**Comment by s8sg** [comment]
Great catch, thanks for reporting this @mikejwhitehead. 

> Happy to submit a PR   

Great 🎉
